Import('env')
from os import path

modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name       = modName+'_'+libName
sources    = env.DWAGlob('*.cc')
incdir     = [env.Dir('#include')]
components = [
	   'common_math',
	   'common_platform',
	   'fb_util_ispc',
	   'render_util',
	   'tbb'
	   ]

# --------------------------------------------------------------------------
publicHeaders = [
              'ActivePixels.h',
              'FbTypes.h',
              'GammaF2C.h',
              'PixelBuffer.h',
              'PixelBufferUtilsGamma8bit.h',
              'ReGammaC2F.h',
              'ReSrgbC2F.h',
              'RunningStats.h',
              'SnapshotUtil.h',
              'SparseTiledPixelBuffer.h',
              'SrgbF2C.h',
              'StatisticalTestSuite.h',
              'StatisticsPixelBuffer.h',
              'TileExtrapolation.h',
              'Tiler.h',
              'VariablePixelBuffer.h',
              ]
env.DWAInstallInclude(publicHeaders, 'scene_rdl2/common/fb_util')
env.DWAUseComponents(components)
env.Prepend (CPPPATH=incdir)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWALinkValidate(name)
