Import('env')

name       = 'pdevunit'
sources    = ['pdevunit.cc']
publicHeaders = ['pdevunit.h']
components = ['cppunit']

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, COMPONENTS=components,
                        CPPPATH=['${INSTALL_DIR}/include'])
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)

env.DWAInstallInclude(publicHeaders, 'scene_rdl2/'+name)
