-- Copyright 2023 DreamWorks Animation LLC
-- SPDX-License-Identifier: Apache-2.0

local data = io.read("*all")

io.write("// Copyright 2023 DreamWorks Animation LLC\n")
io.write("// SPDX-License-Identifier: Apache-2.0\n")
io.write("\n")
io.write("// WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY THE BUILD!\n")
io.write("//          MODIFICATIONS TO IT WILL NOT BE SAVED!\n")
io.write("\n")
io.write("#include <cstdlib>\n")
io.write("\n")
io.write("namespace {\n")
io.write("\n")
io.write("const std::size_t bin2cc_len = " .. tostring(#data) .. ";\n")
io.write("\n")
io.write("const unsigned char bin2cc_data[bin2cc_len] = {\n")
io.write("   ")
for n = 1, #data do
    io.write(string.format(" 0x%02x", string.byte(data, n, n)))
    if n < #data then
        io.write(",")
        if n % 8 == 0 then
            io.write("\n   ")
        end
    end
end
io.write("\n};\n")
io.write("\n")
io.write("} // namespace\n")
io.write("\n")
