import glob
Import('env')
# ------------------------------------------
name       = 'rdl2_json_exporter'
sources = [
    'rdl2_json_exporter.cc'
]

components = [
    'boost_filesystem_mt',
    'boost_program_options_mt',
    'common_except',
    'jsoncpp',
    'render_logging',
    'scene_rdl2',
]
# ------------------------------------------
env.DWAForceWarningAsError()
env.DWAUseComponents(components)
prog = env.DWAProgram(name, sources)
env.Alias("rdl2_json_exporter", prog)
result = env.DWAInstallBin(prog)
