Import('env')
# --------------------------------------------------------------------
name       = 'common_math_ispc'
sources    = env.DWAGlob('*.cc')
ref        = []
components = [
    'math_ispc',
    'render_util',
]
env.DWAUseComponents(components)

sources = [
    'main.cc',
    'Test.cc',
    'TestAsA.cc',
    'TestAutodiff.cc',
    'TestCol3.cc',
    'TestCol4.cc',
    'TestColorSpace.cc',
    'TestConstants.cc',
    'TestMat3.cc',
    'TestMat4.cc',
    'TestQuaternion.cc',
    'TestRandom.cc',
    'TestReferenceFrame.cc',
    'TestVec2.cc',
    'TestVec3.cc',
    'TestVec4.cc',
    'TestXform.cc',
    'TestXformv.cc',
    ]

# for this option to take affect, it must be added *before* we add the ispc sources.
env.AppendUnique(ISPCFLAGS=['--opt=force-aligned-memory'],
                 CPPPATH=[env.Dir('.')])

ispc_objects, ispc_headers = env.IspcShared([
        'Test.ispc',
        'TestAsA.ispc',
        'TestAutodiff.ispc',
        'TestCol3.ispc',
        'TestCol4.ispc',
        'TestColorSpace.ispc',
        'TestConstants.ispc',
        'TestMat3.ispc',
        'TestMat4.ispc',
        'TestQuaternion.ispc',
        'TestRandom.ispc',
        'TestReferenceFrame.ispc',
        'TestVec2.ispc',
        'TestVec3.ispc',
        'TestVec4.ispc',
        'TestXform.ispc',
        ])
sources += ispc_objects

# disable warning #1478: class "std::auto_ptr<CppUnit::TestSuite>" was declared deprecated
if 'icc' in env['CC']:
    env['CXXFLAGS'].append('-wd1478')
elif 'gcc' in env['CC']:
    env['CXXFLAGS'].append('-Wno-conversion') 
    env['CXXFLAGS'].append('-w')

env.DWAForceWarningAsError()

# --------------------------------------------------------------------
ut = env.DWAPdevUnitTest(name, sources, ref, COMPONENTS=components)
