Import('env')
from os import path

modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name       = modName+'_'+libName
sources    = env.DWAGlob('*.cc')
incdir     = [env.Dir('#include')]
components = [
    'render_util',
    'scene_rdl2'
]

# --------------------------------------------------------------------------
publicHeaders = [
    'CacheAllocator.h',
    'CacheDequeue.h',
    'CacheEnqueue.h',
    'CacheUtil.h'
]

env.DWAInstallInclude(publicHeaders, 'scene_rdl2/render/cache')
env.DWAUseComponents(components)
env.Prepend (CPPPATH=incdir)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWALinkValidate(name)
