Import('env')
from os import path

modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name       = modName+'_'+libName
sources    = env.DWAGlob('*.cc')
incdir     = [env.Dir('#include')]
# --------------------------------------------------------------------------
publicHeaders = [
	      'RecDouble.h',	      
	      'RecTick.h',
	      'RecTime.h',
	      'RecTimeLap.h',
	      'RecUInt64.h'
]
env.DWAInstallInclude(publicHeaders, 'scene_rdl2/common/rec_time')
env.Prepend (CPPPATH=incdir)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir)
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')])
env.DWALinkValidate(name)
