Import('env')
# --------------------------------------------------------------------
name       = 'common_simd'
sources    = env.DWAGlob('*.cc')
ref        = []
components = [
              'common_math',
              'cppunit',
              'pdevunit',
              ]

if 'icc' in env['CC']:
    env['CXXFLAGS'].append('-wd2203') # warning: cast discards qualifiers from target type
elif 'gcc' in env['CC']:
    env['CXXFLAGS'].append('-Wno-unused-value');
env.DWAForceWarningAsError()

# --------------------------------------------------------------------
ut = env.DWAPdevUnitTest(name, sources, ref, COMPONENTS=components)
