Import('env')
from os import path

# extract library name from current/parent path
modname = path.basename(path.abspath('..'))
libname = path.basename(path.abspath('.'))
name    = modname + '_' + libname
# --------------------------------------------------------------------------

components = [
    'common_platform',
]
env.DWAUseComponents(components)

# for this option to take affect, it must be added *before* we add the ispc sources.
env.AppendUnique(ISPCFLAGS = ['--opt=force-aligned-memory'])

incdir = [env.Dir('#include'), env.Dir('$INSTALL_DIR/include')]

# --------------------------------------------------------------------------
docHeaders = [
            'asA.isph',
            'autodiff.isph',
            'Col3.isph',
            'Col4.isph',
            'Color.isph',
            'ColorSpace.isph',
            'Constants.isph',
            'Dual.isph',
            'Mat3.isph',
            'Mat4.isph',
            'Math.isph',
            'Quaternion.isph',
            'ReferenceFrame.isph',
            'Typesv.h',
            'Variform.isph',
            'Vec2.isph',
            'Vec3.isph',
            'Vec4.isph',
            'Xform.isph',
            'Xformv.h'
            ]

sources, publicHeaders = env.IspcShared(('Types.ispc', 'Xform.ispc'))
publicHeaders.extend(docHeaders)

env.DWAInstallInclude(publicHeaders, 'scene_rdl2/common/math/ispc')

lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)

env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name,
                             LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWALinkValidate(name)
