Import('env')
# --------------------------------------------------------------------
name       = 'render_util'
sources    = env.DWAGlob('*.cc')
ref        = []
components = [
              'common_math',
              'common_platform',
              'render_util',
              'tbb'
              ]
# --------------------------------------------------------------------
env.DWAForceWarningAsError()
if 'clang' in env['CC']:
    env['CXXFLAGS'].append('-Wno-unused-value')  #W: expression result unused
                                                 #   expanded from macro 'MNRY_VERIFY'

# don't error on unused functions
if 'icc' in env['CC'] and '-wd177' not in env['CXXFLAGS']:
    env['CXXFLAGS'].append('-wd177')

ut = env.DWAPdevUnitTest(name, sources, ref, COMPONENTS=components, TIMEOUT=600)
