Import('env')
from os import path

modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name       = modName+'_'+libName
incdir     = [env.Dir('#include')]
# --------------------------------------------------------------------------
publicHeaders = ['exceptions.h']
env.DWAInstallInclude(publicHeaders, 'scene_rdl2/common/except')
env.DWAComponent(name, CPPPATH=incdir)
env.DWAInstallSConscriptStub(name, CPPPATH=[env.Dir('$INSTALL_DIR/include')])
