Import('env')
from os import path

# extract library name from current/parent path
modname = path.basename(path.abspath('..'))
libname = path.basename(path.abspath('.'))
name    = modname + '_' + libname
# --------------------------------------------------------------------------

components = [
    'common_platform',
    'math_ispc',
]
env.DWAUseComponents(components)

# for this option to take affect, it must be added *before* we add the ispc sources.
env.AppendUnique(ISPCFLAGS = ['--opt=force-aligned-memory'])

incdir = [env.Dir('#include'), env.Dir('$INSTALL_DIR/include')]

# --------------------------------------------------------------------------
docHeaders = [
            'PixelBuffer.hh',
            'VariablePixelBuffer.isph'
            ]

sources, publicHeaders = env.IspcShared(('VariablePixelBuffer.ispc', 'SnapshotUtil.ispc'))
publicHeaders.extend(docHeaders)

env.DWAInstallInclude(publicHeaders, 'scene_rdl2/common/fb_util/ispc')

lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)

env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name,
                             LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include')],
                             COMPONENTS=components)
env.DWALinkValidate(name)
