// Copyright 2023-2024 DreamWorks Animation LLC
// SPDX-License-Identifier: Apache-2.0

#include "test_math.h"

#include <scene_rdl2/pdevunit/pdevunit.h>

#include "test_math.h"
#include "test_math_Color.h"
#include "TestColorSpace.h"
#include "test_math_Mat3.h"
#include "test_math_Mat4.h"
#include "test_math_ReferenceFrame.h"
#include "test_math_Quaternion.h"
#include "test_math_Vec4.h"
#include "test_math_Xform.h"
#include "TestTranscendental.h"
#include "TestViewport.h"

int
main(int argc, char *argv[])
{
    CPPUNIT_TEST_SUITE_REGISTRATION(TestCommonMath);
    CPPUNIT_TEST_SUITE_REGISTRATION(TestCommonMathMat3);
    CPPUNIT_TEST_SUITE_REGISTRATION(TestCommonMathMat4);
    CPPUNIT_TEST_SUITE_REGISTRATION(TestCommonMathReferenceFrame);
    CPPUNIT_TEST_SUITE_REGISTRATION(TestCommonMathQuaternion);
    // TestCommonMathTranscendental is commented out since it's not a unit test per se; instead it uses the unit test
    // mechanism to do error analysis on our transcendental functions. Uncomment to run the tests, then find the
    // results in the LastTest.log file generated by the unit tests.
    //CPPUNIT_TEST_SUITE_REGISTRATION(TestCommonMathTranscendental);
    CPPUNIT_TEST_SUITE_REGISTRATION(TestCommonMathVec4);
    CPPUNIT_TEST_SUITE_REGISTRATION(TestCommonMathXform);
    CPPUNIT_TEST_SUITE_REGISTRATION(TestViewport);
    CPPUNIT_TEST_SUITE_REGISTRATION(TestCommonMathColor);
    CPPUNIT_TEST_SUITE_REGISTRATION(TestCommonColorSpace);
    return pdevunit::run(argc, argv);    
}


