Import('env')

from os import environ
from bart.buildinfo import getRezVersion

# --------------------------------------------------------------------
name       = 'common_math'
sources    = env.DWAGlob('*.cc')
ref        = []
components = [
              'common_math',
              'common_fb_util',
              'render_util',
              'tbb'
              ]

if int(getRezVersion()[0]) < 2:
    env.AppendUnique(CPPDEFINES=['MNRY_ASSERT_THROWS_EXCEPTION'])
else:
    env.AppendUnique(CPPDEFINES=['MNRY_ASSERT_ABORTS'])
env['CXXFLAGS'].append('-DTSLOG_LEVEL=TSLOG_MSG_DEBUG')
env['CXXFLAGS'].append('-DTSLOG_SHOW_FILE')
env.AppendUnique(LIBS=['rt'])
    
if 'icc' in env['CC']:
    env['CXXFLAGS'].append('-wd2203') # warning: cast discards qualifiers from target type
if 'gcc' in env['CC'] and int(environ.get('REZ_GCC_MAJOR_VERSION')) >= 9:
    env['CXXFLAGS'].append('-Wno-deprecated-copy')

env.DWAForceWarningAsError()

# --------------------------------------------------------------------
ut = env.DWAPdevUnitTest(name, sources, ref, COMPONENTS=components)
